export enum BUILDINGS {
    HQ = 'HQ',
    MISSILE_LAUNCHER = 'MISSILE_LAUNCHER',
    AIR_DEFENSE='AA',
    ANTI_PERSONNEL_WEAPONS='ANTI_PERSONNEL_WEAPONS',
    RADAR='RADAR',
    MINEFIELD='MINEFIELD',
    MINE='MINE',
    POWER_PLANT='POWER_PLANT',
    MARINE_CORPS='MARINE_CORPS',
    NUCLEAR_SILO='NUCLEAR_SILO',
}