export enum BUILDINGS {
    HQ = 'HQ', 
    MISSILE_LAUNCHER = 'MISSILE_LAUNCHER', 
    AIR_DEFENSE='AIR_DEFENSE', 
    ANTI_PERSONNEL_WEAPONS='ANTI_PERSONNEL_WEAPONS', 
    RADAR='RADAR', 
    FACTORY='FACTORY', 
    MINEFIELD='MINEFIELD', 
    MINE='MINE', 
    POWER_PLANT='POWER_PLANT', 
    MARINE_CORPS='MARINE_CORPS', 
    NUCLEAR_SILO='NUCLEAR_SILO', 
}

